### ISSUE TITLE
Неверная ссылка на песочницу в третьем задании

### ISSUE THREAD

**Issue by eone666** [bringmetheaugust/welcome_to_TE#1]
Ссылка на песочинцу в [третьем](https://github.com/bringmetheaugust/welcome_to_TE/tree/master/task_3) задании ведет на песочницу для [второго](https://github.com/bringmetheaugust/welcome_to_TE/tree/master/task_2) задания

**Comment by bringmetheaugust** [comment]
@eone666 , да, Вы правильно заметили.
прошу прощение за это недоразумение.

**fixed** https://github.com/bringmetheaugust/welcome_to_TE/commit/31d0ade713b3489605a1ae682424dc436e41759b
